
export const FETCH_REQUEST_FETCHING = 'FETCH_REQUEST_FETCHING'
export const FETCH_REQUEST_ERROR = 'FETCH_REQUEST_ERROR'
export const FETCH_REQUEST_SUCCESS = 'FETCH_REQUEST_SUCCESS'

export const SET_ERRORS = 'SET_ERRORS'

export const SET_SETTINGS = 'SET_SETTINGS'
export const RESET_SETTINGS = 'RESET_SETTINGS'

export const SET_USERDATA = 'SET_USERDATA'
export const UNSET_USERDATA = 'UNSET_USERDATA'

export const FETCH_SINGIN_FETCHING = 'FETCH_SINGIN_FETCHING'
export const FETCH_SINGIN_ERROR = 'FETCH_SINGIN_ERROR'
export const FETCH_SINGIN_SUCCESS = 'FETCH_SINGIN_SUCCESS'

export const FETCH_SINGUP_FETCHING = 'FETCH_SINGUP_FETCHING'
export const FETCH_SINGUP_ERROR = 'FETCH_SINGUP_ERROR'
export const FETCH_SINGUP_SUCCESS = 'FETCH_SINGUP_SUCCESS'

export const FETCH_USER_FETCHING = 'FETCH_USER_FETCHING'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
